version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.1
  aws-cli: circleci/aws-cli@5.4.1

parameters:
  stack-id:
    type: string
    default: ''
  version:
    type: string
    default: 'auto'
  deployment-config:
    type: string
    default: 'standalone.deployment.docker-compose.yml'
  portainer-url:
    type: string
    default: '$DEFAULT_PORTAINER_URL'
  portainer-api-key:
    type: string
    default: '$DEFAULT_PORTAINER_API_KEY'

jobs:
  deploy:
    docker:
      - image: cimg/node:24.10
    resource_class: small
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "${B1_ROLE_ARN}"
          region: "${AWS_REGION}"
      - run:
          name: Get CodeArtifact token
          command: |
            TOKEN=$(aws codeartifact get-authorization-token \
              --domain buildone --domain-owner 653306034207 \
              --region $AWS_REGION --query authorizationToken --output text)
            echo "export CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $BASH_ENV
      - run:
          name: Install CircleCI pacakges
          command: yarn workspaces focus circleci
      - continuation/continue:
          configuration_path: node_modules/@buildone/swat-circleci/defaults/deploy/config.yml
          parameters: '{"app-name":"starter"}'

workflows:
  deploy-setup-workflow:
    jobs:
      - deploy:
          context: 
            - build-defaults