image: gitpod/workspace-node-lts:2024-07-10-08-22-03

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: ignore
    visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: startup
    before: export PATH=${PATH}:${GITPOD_REPO_ROOT}/node_modules/.bin
    init: |
      echo "Installing monorepo packages..." && npm i -g @nestjs/cli && yarn install && gp sync-done packages-install
      echo "Clearing yarn cache..." && yarn cache clear
      echo "Initializing workspace..." && b1 init
      echo "Pulling stack images..." && b1 pull
    command: |
      echo "Starting stack..." && b1 up && gp sync-done b1-up
      echo "Waiting for data import..." && gp sync-await data-import
      echo "Launching application in browser window..." && b1 preview
      echo "Installing extensions..." && b1 extension
  - name: import:data
    before: |
      export PATH=${PATH}:${GITPOD_REPO_ROOT}/node_modules/.bin
    command: |
      echo "Waiting for stack to start..." && gp sync-await b1-up
      echo "Waiting for stack to be operational..." && b1 wait-for-stack
      echo "Running Postgres import..." && b1 import-vanguard true
      echo "Import automation workflows..." && b1 import-automation workflows
      gp sync-done data-import
  - name: install:extensions
    before: |
      export PATH=${PATH}:${GITPOD_REPO_ROOT}/node_modules/.bin
    command: |
      echo "Waiting for stack to start..." && gp sync-await b1-up
      echo "Installing extensions..." && b1 extensions
  - name: watch:app-server-ts
    command: |
      echo "Waiting for stack to start..." && gp sync-await b1-up
      docker logs -f gitpod-app_server_ts-1
  - name: watch:web-app
    command: |
      echo "Waiting for stack to start..." && gp sync-await b1-up
      docker logs -f gitpod-web-app-1

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mikestead.dotenv
    - mhutchie.git-graph
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - stylelint.vscode-stylelint
    - Vue.volar
