enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  'https://buildone-653306034207.d.codeartifact.eu-central-1.amazonaws.com/npm/b1/':
    npmAuthToken: '${CODEARTIFACT_AUTH_TOKEN}'

npmScopes:
  buildone:
    npmRegistryServer: 'https://buildone-653306034207.d.codeartifact.eu-central-1.amazonaws.com/npm/b1/'
  fortawesome:
    npmRegistryServer: 'https://buildone-653306034207.d.codeartifact.eu-central-1.amazonaws.com/npm/b1/'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
