enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  buildone:
    npmAuthToken: "${BUILDONE_TOKEN}"
    npmRegistryServer: "https://npm.cloudsmith.io/buildone/repository/"
  fortawesome:
    npmAuthToken: "${BUILDONE_TOKEN}"
    npmRegistryServer: "https://npm.cloudsmith.io/buildone/repository/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
