version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.1
  aws-cli: circleci/aws-cli@5.4.1

parameters:
  base-revision:
    type: string
    default: origin/develop
  build-all:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/node:24.10
    resource_class: small
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "${B1_ROLE_ARN}"
          region: "${AWS_REGION}"
      - run:
          name: Get CodeArtifact token
          command: |
            TOKEN=$(aws codeartifact get-authorization-token \
              --domain buildone --domain-owner 653306034207 \
              --region $AWS_REGION --query authorizationToken --output text)
            echo "export CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $BASH_ENV
      - run:
          name: Install CircleCI pacakges
          command: yarn workspaces focus circleci
      - run:
          name: Calculate base revision
          command: echo "export BASE_REVISION=`git merge-base HEAD << pipeline.parameters.base-revision >>`" >> $BASH_ENV
      - run:
          name: Detect git changes
          environment:
            BASE_REVISION: $BASE_REVISION
            MAPPING: |
              src/app-server-ts/.* build-app-server-ts true
              src/web-app/.* build-web-app true
              yarn.lock build-cache true
            OUTPUT_PATH: /tmp/pipeline/pipeline-parameters.json
          command: |
            mkdir -p /tmp/pipeline
            echo '{"app-name":"starter", "docker-repository": "653306034207.dkr.ecr.eu-central-1.amazonaws.com/starter"}' > /tmp/pipeline/pipeline-parameters.json
            python3 node_modules/@buildone/swat-circleci/scripts/detect_git_changes.py
      - continuation/continue:
          configuration_path: node_modules/@buildone/swat-circleci/defaults/build/config.yml
          parameters: /tmp/pipeline/pipeline-parameters.json

workflows:
  build-setup-workflow:
    jobs:
      - build:
          context:
            - build-defaults
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
