version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.1
  aws-cli: circleci/aws-cli@5.4.1

parameters:
  version:
    type: string
    default: 'auto'

jobs:
  tag:
    docker:
      - image: cimg/node:24.10
    resource_class: small
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "${B1_ROLE_ARN}"
          region: "${AWS_REGION}"
      - run:
          name: Get CodeArtifact token
          command: |
            TOKEN=$(aws codeartifact get-authorization-token \
              --domain buildone --domain-owner 653306034207 \
              --region $AWS_REGION --query authorizationToken --output text)
            echo "export CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $BASH_ENV
      - run:
          name: Install CircleCI pacakges
          command: yarn workspaces focus circleci
      - continuation/continue:
          configuration_path: node_modules/@buildone/swat-circleci/defaults/tag/config.yml
          parameters: '{"app-name":"starter"}'

workflows:
  tag-setup-workflow:
    jobs:
      - tag:
          context: 
            - build-defaults