import { boolean, date, integer, numeric, pgTable, serial, text, timestamp, varchar } from 'drizzle-orm/pg-core';

export const clients = pgTable('clients', {
  id: serial().primaryKey().notNull(),
  name: varchar({ length: 100 }).notNull(),
  email: varchar({ length: 255 }),
  phone: varchar({ length: 50 }),
  address: text(),
  createdAt: timestamp('created_at', { mode: 'string' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'string' }).defaultNow().notNull(),
  country: varchar({ length: 100 }),
  company: varchar({ length: 255 }),
  date: date(),
  status: varchar({ length: 50 }),
  verified: boolean().default(false),
  activity: integer(),
  representative: varchar({ length: 100 }),
  balance: numeric({ precision: 10, scale: 2 }),
  active: boolean().default(true),
  createdby: varchar({ length: 100 }),
  customerPriority: varchar({ length: 50 }),
  dunsNumber: varchar({ length: 10 }),
  description: text(),
  employees: integer(),
  fax: varchar({ length: 50 }),
  industry: varchar({ length: 50 }),
  lastUpdatedBy: varchar({ length: 100 }),
  parentCompany: varchar({ length: 100 }),
  rating: integer(),
  shippingAddress: text(),
  sla: varchar({ length: 100 }),
  slaExpirationDate: date({ mode: 'string' }),
  slaSerialNumber: varchar({ length: 10 }),
  tickerSymbol: varchar({ length: 20 }),
  type: varchar({ length: 50 }),
  website: varchar({ length: 255 }),
  yearStarted: varchar({ length: 50 })
});
